#!/bin/sh
set -o errexit -o nounset -o pipefail

# Run this script to deploy the rook-ceph operator to Kubernetes.

# This helm repository is undocumented but appears to be where chart versions >= 1.0.0 reside.
# Chart versions < 1.0.0 won't work because they use Kubernetes APIs that are no longer supported e.g. apps/v1beta1
helm repo add rook https://charts.rook.io/release
helm install --namespace=rook-ceph --values=./operator.values operator rook/rook-ceph
