# Git repository server

apiVersion: v1
kind: ConfigMap
metadata:
  name: git-server-keys
  namespace: kier
  labels:
    app: git-server
data:
  keys.pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCbTr+M72gEe39Lr0UEF2mFigbXF/xkDCYwUyhi/owvxYyMqpkEz1qp+i4c8kt+rbE3mfHniFYY0n5UrnKtNzwMtm14fHg4SBdoAvH3sBbiuYajNJUNUQKj/ZhHxFKz++pFEbz6pmEJwpq6XfH2MF3suIBKUzGY7CAwKnLhy1/Y53Zsrem3LLjWvhuxxIkjIPHutZtIq9e+/g9YsVwGQpCZm32z3CEwg7mO0Ldb/LkKfcpmqhUZZOa0dAdLRSq4NgsiZo7djeuCLFtR9N+57ydLpea/3aI95RQrqeGte5tEtNIFQH6OOIXA/e0Z03xdx5WpeFv5MRDEiobOzJCzAdS1 kier@beagle2
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCr5oNVuZMYi1SwOUpIt13uhfSMzpP1e4g7WLjQJPa+vq8zOD2+ryHJgLbN+lw73ZQOVlSc1DZ4aA5DFF9SdPXdIct8hWw5DBqktO2vO7w7i7V68RrsGwcxHfMtbA7kfm1plO8tCcoP3IuWFONysowOhU0CKzwfsvnHex6s+t5GE6Y4KK+aFpzrqRkP2VnkK0nMP+2jeH4AMNEIZg1scO7BCFZZYeBPNLdT3tbnH+z6BPHr1CpT2iEaZEKsjGUPLdoqrXC2fqSFn8PJRCYfRAt3dxV1lQbZ/dt2sUZgzBz9XRhp5WPzWhRv6CVx2DFD3TnLkjQoC/7sHA6NRYJVI5b3 kier@coloris
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOwUC9OqLttu9B4qk+V83vwCBKKgqjwF41BG5fj5wgQ+ kier@saelli
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCvo4MRJHzXAqSNvD3tB34QpYj1nYw7o8pcsZtnGH5EU35hWUrCSAaOEggTy1hO+Y+hc6e0A6ZvSzSyABJh+W35SKVitNQuuGQRdYat2NlJC6hO1OVLsdKyjIvEqEHssXyOr9neSSw/qOthXS0s0UCtvXafVRiVY+IZvuqJduoVHitN9WzSKUjjjZJuc5sup70wI/cDRu9N3smwKQfflC5Kz72YQJ2S7eBPe06FR50RnocUGhCn6k39ZAQYbIc0IIvyO+GEvKBzwOhYwzxzMejupUpcC2VBIDo+akb0rvFFMd7OAmVirxzQy0G8OgNQUF60sztgOOjob0nC5xfTGt6+wRyGCbSfz2kz90AhM5ATbLyXFhRAzwo5L50RfEEQQ6NPTyim49fFtOPhG9SCSugeUaS5pW9jrUbJ/ZaeyO0X8K76orIjWTlA2NpMc+72QA3i/fZsbYupGkP1bynBmM2FIxb6ZX5qkYM8MWMNj0NdmxnDroxYqZ0wmFoepUcqvGpxuSkIRc+EYHOrWRlY+MTy4tkhlr4xMC35Uu90xVOA6SWbHTfKbktO1ATijOClsU7EW3mv6xwuWnYkCajdWnumz1RUIrCb81hlPi6t4r8licenevNlMWy3LN+ZOYTRy/7Znq7esrm1Qyuhp1phvTEck/cEYpuajIjj8jjV0sRVw== PasswordStore@MotoG5-201803
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM5NZWLLmLVS+p+qW5WJo0AwZTi+og6xiOqdDK/WAc1x ConnectBot@MotoG5-201803
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcD2fIBle9XgHokzJ4Y0NLJXVDZoUxjXANZkK9/aXEgPZrDLW8qMtXBEPPvmxRIqOJO8idnxseBZScCQdnJghPWGnK9IJ6be4s0Dwcxy+ZMTVpyQLUPXCLAbInZhXkD+fkm86p1dLLIvF6fAE1EkKSqImqfOURfTIiFdBseY6mLV1f2Hx5pa3IF1Eh3T7fAQEsmXt+doDdQFZpdwVhBrvPKy0VpHTPB4JkUAwLBu9D84dwrz8pQg9AsQDBIAJhOj81yw2sOO/+wiXY/mLeAiwyhNULbYYIM0ZtT5qzlpHy47gwdNaaFpvbc9C2DGsyymLhQW2v5WUQZMdWKlo61wmDQFagZVYZUflwD0ikZKqMBRcVV7uHuD3e3vTjPR+A/ArFFA9BIRsvHE/0y6e9vTogGSfC/tswiftBhiWrc09dAEyLZwmcJpHEIkd2QrCwYSs9EZw6L+3g9gPN2oeXI8dvhz/IBIjvmFYl0uNvdxRb5FfHeJuCJKI52dLfsgvy9YHb4JarDKWlYZYApHa69x+OEdUJ82OaXAsoRjIP1kPKIsv9WjdUzcDimDdD/nHiIrY0XBrsvAHTyVmz6nXemHoN+4xTByCvmycuo3G1XLd1H0Xofw6OigaQPihoDgB7OVZEKTBrJTlrk7H+v8YJvaeRt21F3suyZNyuVj5SZRVn3Q== PasswordStore@kier-pixel4-201911
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDocl4lkRhqceWgZRPr/Cl0C7ryUg4p5F7p0m5exTLjXptM5i+4HvZaKrP7a529J3+TYD0Ymgciad7Nc/OwHPNJOik3rx+3a6ttP03TuozoIsizqwOopOwkgpUrG8L0r3YwdmYcEShFiK6KywZg9hlolZLE3K87smdHasi4+wcDzXly+A3sfMsWz/DacF7WWF9Hu+XxmoqIhsg89y2Z0+4J8/HbrW0jHefE2cSrL1UDCnR1T/wFJNqnTEEDsLEW2VlHb7wJPvY+v2fA6RBY93ZIjifAfelEFlhnTb4Csk+YkK8B2UslaNNVNIluODLJ3g9rgDWen3YyDfRWCPfyLLCJFgcTsHR2GjDn0bP40M8YbEcNDFoC4t6J/9VFPTDvjbrkWz8jYe0QcWH3spYq2wx5GA+UIdYSndoSus9BvcxjU5dIJKeERBldsw0Ct6Sykp6mIhEq4/fcckcxhqtqT65gke1BjSb93aFewsh5CK7AvlrTFgnH4K3RFFebBT/GGUgPwApw6lgGZSTbsCNqxDABgYG3JavLOpm+NEHwv2Qh0YhTIOlznx98HqXkvf8072bNdKoBFBlJ5uayXWXgPvnB5G8H9q70iTSfwiOQMcPAoF8XjqtGy4VPxLo1zYQqZ02SacwTf9FQDiRxMGupE3FDcghngHKvfnmc4H2faEx96Q== PasswordStore@kier-pixel4-202007
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINB+RmhUfSIFAk5PQGg0aDAQxPo9tYVgSt2lW6Xq3/GN kier@coloris-wsl2
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOaxfDG7fhcfh1kcK/SO6vmxkS2YkbIc7qRymg2sv3YU root@ptolemy
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMEa6zl6vjffZy3ez3CTd2nB3WlCI99VtBOEWXbgl/2M kier@fingerbib

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-server
  namespace: kier
  labels:
    app: git-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-server
  template:
    metadata:
      labels:
        app: git-server
    spec:
      nodeSelector:  # remove when no longer dependent on /home/k8s
        kubernetes.io/hostname: beagle2
      containers:
      - name: git-server
        image: kierdavis/git-server-docker:latest
        imagePullPolicy: Always
        ports:
        - name: ssh
          containerPort: 22
        volumeMounts:
        - name: keys
          mountPath: /git-server/keys
        - name: repos
          mountPath: /git-server/repos
      volumes:
      - name: keys
        configMap:
          name: git-server-keys
      - name: repos
        hostPath:
          path: /home/k8s/kier/git-repos

---

apiVersion: v1
kind: Service
metadata:
  name: git-server
  namespace: kier
  labels:
    app: git-server
spec:
  type: NodePort
  selector:
    app: git-server
  ports:
  - name: ssh
    port: 22
    targetPort: ssh
    nodePort: 30002
    protocol: TCP
