# mopidy music playback server

apiVersion: v1
kind: ConfigMap
metadata:
  name: mopidy-config
  namespace: kier
  labels:
    app: mopidy
data:
  mopidy.conf: |
    [core]
    data_dir = /var/lib/mopidy
    [local]
    media_dir = /music
    [audio]
    output = queue ! pulsesink
    [m3u]
    playlists_dir = /var/lib/mopidy/playlists
    [http]
    hostname = 0.0.0.0
    [mpd]
    hostname = 0.0.0.0
    #[gmusic]
    #username=USERNAME
    #password=PASSWORD
    #[soundcloud]
    #auth_token=TOKEN

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mopidy
  namespace: kier
  labels:
    app: mopidy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mopidy
  template:
    metadata:
      labels:
        app: mopidy
    spec:
      nodeSelector:
        kubernetes.io/hostname: butterfly
      containers:
      - name: mopidy
        image: wernight/mopidy
        command: ["mopidy", "--config", "/config/mopidy.conf:/config-secret/mopidy.conf"]
        volumeMounts:
        - name: pulseaudio-socket
          mountPath: /run/pulse/native
        - name: pulseaudio-cookie
          mountPath: /run/pulse/cookie
        - name: config
          mountPath: /config
          readOnly: true
        - name: config-secret
          mountPath: /config-secret
          readOnly: true
          # TODO: mount a PV at /var/lib/mopidy for the database
          # TODO: mount music at /music
        env:
        - name: PULSE_SERVER
          value: unix:/run/pulse/native
        - name: PULSE_COOKIE
          value: /run/pulse/cookie
        ports:
        - name: http
          containerPort: 6680
        - name: mpd
          containerPort: 6600
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      volumes:
      - name: pulseaudio-socket
        hostPath:
          path: /run/pulse/native
      - name: pulseaudio-cookie
        hostPath:
          path: /run/pulse/.config/pulse/cookie
      - name: config
        configMap:
          name: mopidy-config
      - name: config-secret
        secret:
          secretName: mopidy-config

---

apiVersion: v1
kind: Service
metadata:
  name: mopidy
  namespace: kier
  labels:
    app: mopidy
spec:
  type: NodePort
  selector:
    app: mopidy
  ports:
  - name: http
    port: 6680
    targetPort: http
  - name: mpd
    port: 6600
    targetPort: mpd
