apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: kier
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 2
  dataPools:
  - replicated:
      size: 2
  metadataServer:
    activeCount: 1
