apiVersion: v1
kind: ConfigMap
metadata:
  name: raupack
  namespace: shared
  labels:
    app: raupack
data:
  server.properties: |
    #Minecraft server properties
    allow-flight=false
    allow-nether=true
    broadcast-console-to-ops=true
    broadcast-rcon-to-ops=true
    difficulty=hard
    enable-command-block=false
    enable-query=false
    enable-rcon=false
    enforce-whitelist=false
    force-gamemode=false
    function-permission-level=2
    gamemode=survival
    generate-structures=true
    generator-settings=
    hardcore=false
    level-name=world
    level-seed=909
    level-type=default
    max-build-height=256
    max-players=20
    max-tick-time=60000
    max-world-size=29999984
    motd=Bridgendale: raupack
    network-compression-threshold=256
    online-mode=true
    op-permission-level=4
    player-idle-timeout=0
    prevent-proxy-connections=false
    pvp=false
    query.port=25565
    rcon.password=
    rcon.port=25575
    resource-pack=
    resource-pack-sha1=
    server-ip=
    server-port=25565
    snooper-enabled=true
    spawn-animals=true
    spawn-monsters=true
    spawn-npcs=true
    spawn-protection=16
    use-native-transport=true
    view-distance=10
    white-list=true
  ops.json: |
    [
      {
        "uuid": "5eda9ae1-f168-40f8-a653-292dfea30e86",
        "name": "kierdavis",
        "level": 4,
        "bypassesPlayerLimit": true
      },
      {
        "uuid": "0f8edc39-5243-4f2d-b8a2-fa3b40c80402",
        "name": "rauyran",
        "level": 4,
        "bypassesPlayerLimit": true
      },
      {
        "uuid": "fa3050fb-5a44-4930-9c13-2c04a27474fb",
        "name": "Kahlah",
        "level": 4,
        "bypassesPlayerLimit": true
      }
    ]
  whitelist.json: |
    [
      {
        "uuid": "5eef6e38-ac1e-49dd-88d9-61aa27e95afc",
        "name": "Blackjot"
      },
      {
        "uuid": "d3bd6638-b6b1-452f-8d56-ccfaa301a578",
        "name": "polardusk"
      },
      {
        "uuid": "5eda9ae1-f168-40f8-a653-292dfea30e86",
        "name": "kierdavis"
      },
      {
        "uuid": "3bc81c93-6ce1-4032-b207-5d32d67c50d6",
        "name": "archinot"
      },
      {
        "uuid": "0f8edc39-5243-4f2d-b8a2-fa3b40c80402",
        "name": "rauyran"
      },
      {
        "uuid": "fa3050fb-5a44-4930-9c13-2c04a27474fb",
        "name": "Kahlah"
      },
      {
        "uuid": "294db196-de5f-4855-ab6f-1def8e48ef2c",
        "name": "freyadavis"
      }
    ]



---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: raupack-world
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /volumes/raupack/world
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - beagle2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raupack-world
  namespace: shared
spec:
  storageClassName: local-storage
  volumeName: raupack-world
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: raupack
  namespace: shared
  labels:
    app: raupack
spec:
  selector:
    matchLabels:
      app: raupack
  replicas: 1
  template:
    metadata:
      labels:
        app: raupack
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: raupack
        command: ["sh","-c"]
        args:
          - |
            cp /config-ro/* /
            ./start.sh
        image: iandavis/raupack:latest
        imagePullPolicy: Always
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        volumeMounts:
        - name: world
          mountPath: /world
        - name: config
          mountPath: /config-ro
        resources:
          requests:
            cpu: 1
            memory: 4G
          limits:
            cpu: 2
            memory: 6G
      volumes:
      - name: config
        configMap:
          name: raupack
      - name: world
        persistentVolumeClaim:
          claimName: raupack-world
---

apiVersion: v1
kind: Service
metadata:
  name: raupack
  namespace: shared
  labels:
    app: raupack
spec:
  type: NodePort
  selector:
    app: raupack
  ports:
  - name: minecraft
    port: 25565
    targetPort: minecraft
    nodePort: 30005
    protocol: TCP
