apiVersion: v1
kind: ConfigMap
metadata:
  name: valhelsia
  namespace: shared
  labels:
    app: valhelsia
data:
  server.properties: |
    #Minecraft server properties
    allow-flight=false
    allow-nether=true
    broadcast-console-to-ops=true
    broadcast-rcon-to-ops=true
    difficulty=easy
    enable-command-block=false
    enable-query=false
    enable-rcon=false
    enforce-whitelist=false
    force-gamemode=false
    function-permission-level=2
    gamemode=survival
    generate-structures=true
    generator-settings=
    hardcore=false
    level-name=world
    level-seed=
    level-type=default
    max-build-height=256
    max-players=20
    max-tick-time=60000
    max-world-size=29999984
    motd=Bridgendale: Valhelsia
    network-compression-threshold=256
    online-mode=true
    op-permission-level=4
    player-idle-timeout=0
    prevent-proxy-connections=false
    pvp=true
    query.port=25565
    rcon.password=
    rcon.port=25575
    resource-pack=
    resource-pack-sha1=
    server-ip=
    server-port=25565
    snooper-enabled=true
    spawn-animals=true
    spawn-monsters=true
    spawn-npcs=true
    spawn-protection=16
    use-native-transport=true
    view-distance=10
    white-list=true
  ops.json: |
    [
      {
        "uuid": "5eda9ae1-f168-40f8-a653-292dfea30e86",
        "name": "kierdavis",
        "level": 4,
        "bypassesPlayerLimit": true
      },
      {
        "uuid": "0f8edc39-5243-4f2d-b8a2-fa3b40c80402",
        "name": "rauyran",
        "level": 4,
        "bypassesPlayerLimit": true
      }
    ]

---

# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: valhelsia
#   namespace: shared
#   labels:
#     app: valhelsia
# spec:
#   selector:
#     matchLabels:
#       app: valhelsia
#   serviceName: valhelsia
#   replicas: 0
#   template:
#     metadata:
#       labels:
#         app: valhelsia
#     spec:
#       terminationGracePeriodSeconds: 300
#       containers:
#       - name: valhelsia
#         image: kierdavis/valhelsia:latest
#         ports:
#         - name: minecraft
#           containerPort: 25565
#           protocol: TCP
#         volumeMounts:
#         - name: minecraft
#           mountPath: /minecraft
#         - name: config
#           mountPath: /config
#         resources:
#           requests:
#             cpu: 1
#             memory: 4G
#           limits:
#             cpu: 2
#             memory: 6G
#       volumes:
#       - name: config
#         configMap:
#           name: valhelsia
#   volumeClaimTemplates:
#   - metadata:
#       name: minecraft
#     spec:
#       accessModes: [ReadWriteOnce]
#       storageClassName: rook-edgefs-nfs
#       resources:
#         requests:
#           storage: 10Gi

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: valhelsia
#   namespace: shared
#   labels:
#     app: valhelsia
# spec:
#   type: NodePort
#   selector:
#     app: valhelsia
#   ports:
#   - name: minecraft
#     port: 25565
#     targetPort: minecraft
#     nodePort: 30005
#     protocol: TCP
