apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: dracona-db-backup
  namespace: kier-dev-2
spec:
  generateBucketName: dracona-db-backup
  storageClassName: ceph-replicated-bucket

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dracona-db-backup
  namespace: kier-dev-2
  labels:
    app: dracona-db-backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dracona-db-backup
  template:
    metadata:
      labels:
        app: dracona-db-backup
    spec:
      containers:
      - name: dracona-db-backup
        image: kierdavis/postgres-backup-s3
        env:
        - name: POSTGRES_HOST
          value: dracona-db-postgresql.kier-dev-2.svc
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: POSTGRES
        - name: POSTGRES_DATABASE
          value: dracona
        - name: S3_ENDPOINT  # TODO: take from configmap
          value: http://rook-ceph-rgw-replicated.rook-ceph.svc/
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: dracona-db-backup
              key: AWS_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: dracona-db-backup
              key: AWS_SECRET_ACCESS_KEY
        - name: S3_REGION
          valueFrom:
            configMapKeyRef:
              name: dracona-db-backup
              key: BUCKET_REGION
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: dracona-db-backup
              key: BUCKET_NAME
        - name: S3_PREFIX
          value: "1"
        - name: SCHEDULE
          value: "@daily"

