# A tiny deployment + service + ingress setup that serves a "hello, world!" webpage over HTTP.
# https://helloworld.kierdavis.com/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: kier-dev-2
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: kierdavis/helloworld:latest
        ports:
        - name: http
          containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: kier-dev-2
  labels:
    app: helloworld
spec:
  selector:
    app: helloworld
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: helloworld
  namespace: kier-dev-2
  labels:
    app: helloworld
  annotations:
    kubernetes.io/ingress.class: nginx-external
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: helloworld.kierdavis.com
    http:
      paths:
      - backend:
          serviceName: helloworld
          servicePort: http
  tls:
  - hosts:
    - helloworld.kierdavis.com
    secretName: helloworld-tls
