- hosts: beagle2
  remote_user: root
  tasks:
  - name: Install/upgrade wireguard
    apt:
      name: wireguard-tools
      state: latest
  - name: Configure wireguard interface
    template:
      src: files/beagle2-wg-k8s.conf.j2
      dest: /etc/wireguard/wg-k8s.conf
      owner: root
      group: root
      mode: '0600'
    register: wireguard_config
  - name: (Re)start wireguard interface
    service:
      name: wg-quick@wg-k8s
      state: restarted
    when: wireguard_config.changed
  - name: Install/upgrade kubeadm
    apt:
      name: kubeadm
      state: latest
  - name: Start kubernetes
    shell:
      cmd: kubeadm init --apiserver-advertise-address=172.27.0.1 --control-plane-endpoint=172.27.0.1 > /var/log/kubeadm-init.log
      creates: /etc/kubernetes/kubelet.conf
  - name: Install kubeconfig for user root
    copy:
      remote_src: true
      src: /etc/kubernetes/admin.conf
      dest: /root/.kube/config
      owner: root
      group: root
      mode: '0600'
  - name: Install kubeconfig for user kier
    copy:
      remote_src: true
      src: /etc/kubernetes/admin.conf
      dest: /home/kier/.kube/config
      owner: kier
      group: kier
      mode: '0600'
  - name: Install kubeconfig for user iand
    copy:
      remote_src: true
      src: /etc/kubernetes/admin.conf
      dest: /home/iand/.kube/config
      owner: iand
      group: iand
      mode: '0600'
  - name: Make node schedulable
    command: kubectl taint nodes --all node-role.kubernetes.io/master-
    ignore_errors: true
  - name: Download a copy of the configuration repo
    git:
      repo: https://github.com/kierdavis/k8s-config
      dest: /root/k8s-config
  - name: Install python packages needed for ansible to manage kubernetes resources
    pip:
      name:
      - openshift
      - requests
  - name: Install helm
    shell:
      cmd: |
        mkdir -p /opt/helm
        cd /opt/helm
        curl -L https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz | tar -xz
        ln -s /opt/helm/linux-amd64/helm /usr/local/bin/helm
      creates: /usr/local/bin/helm
  - name: Start Weave Net (the container networking plugin)
    k8s:
      state: present
      src: /root/k8s-config/manifests/kube-system/weave.yaml
  - name: Create ingress namespace
    k8s:
      state: present
      src: /root/k8s-config/manifests/ingress/namespace.yaml
  - name: Create ingress controller
    command: /root/k8s-config/manifests/ingress/nginx-external.deploy up
  - name: Create resource definitions for certificate manager
    k8s:
      state: present
      src: /root/k8s-config/manifests/ingress/cert-manager-crds.yaml
  - name: Create certificate manager
    command: /root/k8s-config/manifests/ingress/cert-manager.deploy up
  - name: Create certificate issuers
    k8s:
      state: present
      src: /root/k8s-config/manifests/ingress/cert-manager-issuers.yaml
